### ISSUE TITLE
Crash when "fab" is used as an id for SpeedDialView

### ISSUE THREAD

**Issue by Ethan1983** [leinardi/FloatingActionButtonSpeedDial#112] opened 2019-02-14 12:39 UTC
Setting "fab" as the id causes the app to crash on orientation change. If fab is meant for internal use, please document the same.

<com.leinardi.android.speeddial.SpeedDialView
                android:id="@+id/fab"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="bottom|end"
                app:sdOverlayLayout="@id/overlay"
                app:layout_behavior="@string/speeddial_scrolling_view_snackbar_behavior"
                app:sdMainFabOpenedSrc="@drawable/ic_fab_done"
                app:sdMainFabClosedSrc="@drawable/ic_fab_add" />

java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class com.google.android.material.j.a instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/fab. Make sure other views do not use the same id.
        at android.view.View.onRestoreInstanceState(View.java:18636)
        at com.leinardi.android.speeddial.SpeedDialView.onRestoreInstanceState(Unknown Source:93)

**Comment by leinardi** [comment] 2019-03-10 09:17
Duplicate of #100.

**Closed as completed by leinardi** 2019-03-10 09:17 UTC
Labels: Priority: High, Type: Enhancement
