### ISSUE TITLE
FAB touch effect creates square shadow on API 22

### ISSUE THREAD

**Issue by akwizgran** [leinardi/FloatingActionButtonSpeedDial#94] opened 2018-09-27 09:41 UTC
On the Moto G 2014 (API 22), the touch effect drawn behind the FAB creates a square shadow that rotates as the speed dial opens, giving the appearance of a rotating square or diamond attached to the back of the FAB.

**Comment by akwizgran** [comment] 2018-09-27 09:48
Here's a screenshot as the speed dial is closing - you can see the square shadow rotating back to its original orientation.

![still.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5baca32735dc3600131efd31/125516c66e82c728ace21e0d46fb80932f8ec1e5cdf9ad4cae58f3806b1c65262807fb2823d6e27be6112a04595f4ead135a0911f4fc8139baa47e21d40854b088270a36d43703aeb8881eba02b2208f4e83bebc824ec0fa70.jpg)

**Comment by akwizgran** [comment] 2018-09-27 09:49
We're using the overlay in this screenshot, but the issue also happens without the overlay.

**Comment by leinardi** [comment] 2018-09-27 10:47
Hi @akwizgran, unfortunately this is an issue of the `FloatingActionButton` from the Design support library. You should get the same issue if you use that directly. This is something that Google has to fix and, looking at what they have done with [similar issues](https://issuetracker.google.com/issues/77303906) I have reported, I doubt they will ever do it.

**Comment by akwizgran** [comment] 2018-09-27 14:41
Thanks @leinardi! It seems the issue is less noticable on our other FABs because they don't rotate. Is there any way we can suppress the rotation or remove the ripple effect from the FAB?

**Comment by leinardi** [comment] 2018-09-28 07:43
The rotation of the fab can be controlled using the  `setMainFabAnimationRotateAngle()` or the XML attribute `sdMainFabAnimationRotateAngle`.
Regarding the ripple effect, I don't know how to remove it, but it should be the same as the Google FAB, just apply the same changes to it with `mSpeedDial.getMainFab()`.

**Comment by kuraydev** [comment] 2018-10-12 10:55
+1. I think priority should be high for this issue. It really looks terrible like that :) 
Also thank you so much for this library.

**Comment by Zaldroc** [comment] 2019-03-21 17:28
Did anyone find a fix for this?

**Comment by QuentinLB** [comment] 2019-10-14 10:31
The [issue](https://issuetracker.google.com/issues/77303906) is marked as resolved and I can confirm that the FAB is working well on a 5.1.1(API 22) tablet with `com.google.android.material:material:1.1.0-beta01`, no square ripple with a basic FAB even after a size update.

The only workaround I found was to disable the ripple effect altogether.

```kotlin
val speedDialView = view.findViewById<SpeedDialView>(R.id.fab_layer_toggle)
speedDialView.mainFab.rippleColor = Color.TRANSPARENT
val fabWithLabelView = addActionItem(SpeedDialActionItem.Builder(R.id.fab_no_label, R.drawable.ic_battery_60_black_24dp).create())
fabWithLabelView!!.fab.rippleColor = Color.TRANSPARENT
```
I would really appreciate if anyone from the project could have another look on the issue. I would do it myself but I just don't have the time right now on the project I'm trying to integrate the speed dial, maybe in two weeks depending on how much the workaround bother the stakeholders I may have time to make a PR but any help / pointers are appreciated.

Thanks for the good work.

**Comment by QuentinLB** [comment] 2019-10-15 07:31
Sorry we won't use speeddial.

**Comment by leinardi** [comment] 2019-10-19 07:47
Confirmed solved using `com.google.android.material:material`.

**Closed as completed by leinardi** 2019-10-19 07:47 UTC
Labels: Type: Bug, Priority: Medium, Status: Blocked

**Comment by QuentinLB** [comment] 2019-10-22 12:23
@leinardi I just saw that you closed the issue and I'm afraid I wasn't clear enough when I made my previous post. I did saw the same square ripple issue on my 5.1.1 tablet, that's how I found this issue in the beginning. 
Because I was trying different FAB configurations, I mentioned google's FAB because I could confirm that the issue wasn't coming from it directly since I didn't see the square ripple using it.

**Comment by leinardi** [comment] 2019-10-22 13:23
I close this issue because I'm not able to reproduce it anymore using `com.google.android.material:material`. Have you tried with that as well? Do you have the same issue using the FAB SpeedDial sample app?

**Comment by QuentinLB** [comment] 2019-10-23 08:12
I didn't tried with the FAB SpeedDial sample app, but I did tried on my own code and I still had the issue even with `com.google.android.material:material:1.1.0-beta01`.

As I said I do not intend to use FAB SpeedDial for now it was just to give you more informations in hope to help you narrow down the problem.

**Comment by BrightVan** [comment] 2020-02-25 07:12
```
public static void fixSpeedDialFab_5_x(@NonNull SpeedDialView speedDialView) {
        if (Build.VERSION.SDK_INT > 22 || Build.VERSION.SDK_INT < 21) {
            return;
        }
        speedDialView.getMainFab().setRippleColor(Color.TRANSPARENT);
        Class speedDialViewClass = speedDialView.getClass();
        try {
            Field fabWithLabelViewsField = speedDialViewClass.getDeclaredField("mFabWithLabelViews");
            fabWithLabelViewsField.setAccessible(true);
            Object targetObject = fabWithLabelViewsField.get(speedDialView);
            if (targetObject instanceof List) {
                List<FabWithLabelView> fabWithLabelViews = (List<FabWithLabelView>) targetObject;
                if (!fabWithLabelViews.isEmpty()) {
                    for (FabWithLabelView fabWithLabelView : fabWithLabelViews) {
                        fabWithLabelView.getFab().setRippleColor(Color.TRANSPARENT);
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
